[package]
name = "playground"
version = "0.0.1"
authors = ["The Rust Playground"]
resolver = "2"

[profile.dev]
codegen-units = 1
incremental = false

[profile.release]
codegen-units = 1
incremental = false
