[package]
edition = "2021"
name = "modify-cargo-toml"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toml = "0.5"

[dependencies.serde]
features = ["derive"]
version = "1.0"
